SNANA_TO_TAXONOMY = {
    'AGN': 'AGN',
    'CART': 'CART',
    'Cepheid': 'Cepheid',
    'd-Sct': 'Delta Scuti',
    'dwarf-nova': 'Dwarf Novae',
    'EB': 'EB',
    'ILOT': 'ILOT',
    'KN_B19': 'KN',
    'KN_K17': 'KN',
    'Mdwarf-flare': 'M-dwarf Flare',
    'PISN': 'PISN',
    'RRL': 'RR Lyrae',
    'SLSN-I+host': 'SLSN',
    'SLSN-I_no_host': 'SLSN',
    'SNIa-91bg': 'Ia-91bg',
    'SNIa-SALT2': 'Ia',
    'SNIax': 'Iax',
    'SNIb+HostXT_V19': 'Ib/c',
    'SNIb-Templates': 'Ib/c',
    'SNIcBL+HostXT_V19': 'Ib/c',
    'SNIc+HostXT_V19': 'Ib/c',
    'SNIc-Templates': 'Ib/c',
    'SNIIb+HostXT_V19': 'II',
    'SNII+HostXT_V19': 'II',
    'SNIIn+HostXT_V19': 'II',
    'SNII-NMF': 'II',
    'SNIIn-MOSFIT': 'II',
    'SNII-Templates': 'II',
    'TDE': 'TDE',
    'uLens-Binary': 'uLens',
    'uLens-Single-GenLens': 'uLens',
    'uLens-Single_PyLIMA': 'uLens',
}
